# Generated by Django 3.0.3 on 2020-02-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='idade',
            field=models.IntegerField(default=0),
        ),
    ]
